global:
  scrape_interval: 15s
  evaluation_interval: 5s
  scrape_timeout: 10s
  external_labels:
    environment: production

# rule_files:
#   - /etc/prometheus/rules/record.rules.yaml
#   - /etc/prometheus/rules/alert.rules.yaml

# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#             - alertmanager:9093

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: node_exporter
    scrape_interval: 5s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["41.89.195.106:9100"]

  - job_name: cAdvisor
    scrape_interval: 5s
    static_configs:
      - targets: ["cadvisor:8080"]